### ISSUE TITLE
Option to allow root path for editor commands

### ISSUE THREAD

**Issue by kameshsampath** [openshift-evangelists/intro-katacoda#103]
When adding the ``src/main/java/com/example/Demo.java``{{open}} there is no option for providing root path, since in case of multi module projects  it will be very handy to have something like ``src/main/java/com/example/Demo.java``{{/root/projects/mydemo open}} where `/root/projects/mydemo` is the root path under which `src/main/java/com/example` may reside.  

Right now only options are `uieditorpath` attribute in `index.json` which is ideal in case of single module project.

**Comment by BenHall** [comment]
This might be confusing from a users point of view as it's not clear which project the path is referring too compared to `mydemo/src/main/java/com/example/Demo.java`

**Comment by kameshsampath** [comment]
that's a valid point !
