### ISSUE TITLE
Invalid Request

### ISSUE THREAD

**Issue by ed4becky** [openshift-evangelists/intro-katacoda#106]
Trying the tutorial, and when I login to the web console for the first time (developer/developer) it tells me invalid request

**Comment by thesteve0** [comment]
Which scenario are you talking about?
Thanks
Steve

**Comment by GrahamDumpleton** [comment]
If it is what I think you are talking about, it happens some times, especially if you have been doing multiple scenarios. If you click the link it shows for console again and login again it should be good. I suspect it is something to do with cookies left over from a prior katacoda session.

**Comment by GrahamDumpleton** [comment]
Assuming this was a transient issue, closing.
