### ISSUE TITLE
Getting Started with OpenShift for Developers step 6

### ISSUE THREAD

**Issue by birdjumper** [openshift-evangelists/intro-katacoda#110]
"To deploy the application you are again going to use the Add to Project feature of the OpenShift web console, so ensure you have the OpenShift web console open and that you are in the project called myproject. Find and select the Add to Project link in the top menu bar for the project. This time, rather than using Deploy Image you want to use Browse Catalog."

When I click on Browse catalog, I get the following message:
"No images or templates are loaded for this project or the shared openshift namespace. An image or template is required to add content."

Please assist.

**Comment by GrahamDumpleton** [comment]
Yep, we are finding this has been happening lately when environments start up slowly. We have a fix, but haven't as yet applied it. If you reload the page so you start over, chances are that it will work the next time. Just check the catalog as soon as you create the project to see if has loaded them correctly.

**Comment by GrahamDumpleton** [comment]
@BenHall This is actually with image streams in 3.6 image, not templates. That scenario doesn't load any templates. So fix I had in mind will not work. That would imply there is an issue with ``launch.sh`` in commands:

```
echo 'oc create namespace openshift > /dev/null 2>&1' >> ~/.launch.sh
echo 'oc create -f /openshift/image-streams-centos7.json --namespace=openshift > /dev/null 2>&1' >> ~/.launch.sh
```

For the loading of the image streams to not work, the project creation can't have happened immediately or ``/openshift/image-streams-centos7.json`` can't now exist in the 3.6 image, yet as I understand it, the JSON file is baked into the image.

I would have thought``oc create namespace`` would only return when was created, or is that also only going to queue the creation, meaning that if things slow, by time run next command may not exist.

So can't actually explain this particular case, not the same as template loading in ``env-init.sh``.

**Comment by birdjumper** [comment]
Thanks for the swift reply. I'll give it another try and report back if it still doesn't work.

**Comment by birdjumper** [comment]
OK, managed to get to the end of the tutorial this time.
Thanks for the support.

**Comment by GrahamDumpleton** [comment]
Believe the solution for this was implemented, closing.
