### ISSUE TITLE
	Normal	Failed binding 	no persistent volumes available for this claim and no storage class is set

### ISSUE THREAD

**Issue by pennpeng** [openshift-evangelists/intro-katacoda#113]
Normal | Failed binding | no persistent volumes available for this claim and no storage class is set
-- | -- | --

**Comment by GrahamDumpleton** [comment]
What scenario are you trying to use? Are you following the set instructions or just experimenting on your own?

**Comment by GrahamDumpleton** [comment]
Going to close this. Persistent storage is only allocated in playground environments, or specific scenarios which need them, such as that on transferring files.
