### ISSUE TITLE
dont working

### ISSUE THREAD

**Issue by jkaczmarzynski** [openshift-evangelists/intro-katacoda#115]

**Comment by mhausenblas** [comment]
@jkaczmarzynski thanks for raising this issue. What exactly is not working? Which scenario did you try? I just gave https://learn.openshift.com/introduction/getting-started/ a spin and worked as expected.

**Comment by jkaczmarzynski** [comment]
I go int this link https://learn.openshift.com/introduction/getting-started/ than i click on star button and nothing happends. When i log in with my email and password still the same
 
W dniu 2017-12-29 15:11:11 użytkownik Michael Hausenblas <notifications@github.com> napisał:
@jkaczmarzynski thanks for raising this issue. What exactly is not working? Which scenario did you try? I just gave https://learn.openshift.com/introduction/getting-started/ a spin and worked as expected.

**Comment by BenHall** [comment]
Could you please provide a screenshot of the login prompt? We shouldn't be
prompting for your email/password.

**Comment by mhausenblas** [comment]
Yes, what Ben said, a screen shot would be helpful. Also, I'm not sure I understand what you mean with the 'star button'. See my screen shot, when you scroll down you hit the 'START SCENARIO' button and it will work as per usual.
<img width="1439" alt="lointro" src="https://user-images.githubusercontent.com/52594/34439523-7de6a38a-eca6-11e7-8e8a-87f497133fda.png">

**Comment by jkaczmarzynski** [comment]
W dniu 2017-12-29 15:35:55 użytkownik Ben Hall <notifications@github.com> napisał:
Could you please provide a screenshot of the login prompt? We shouldn't be
prompting for your email/password.

**Comment by jkaczmarzynski** [comment]
I just send screenshots to Ben. And yes, I mean start scenario, my mistake
 
W dniu 2017-12-29 15:42:48 użytkownik Michael Hausenblas <notifications@github.com> napisał:
Yes, what Ben said, a screen shot would be helpful. Also, I'm not sure I understand what you mean with the 'star button'. See my screen shot, when you scroll down you hit the 'START SCENARIO' button and it will work as per usual.

**Comment by jkaczmarzynski** [comment]
And what else i want to say is that i was using this training and everything was working.  It was more or less a week ago
W dniu 2017-12-29 15:42:48 użytkownik Michael Hausenblas <notifications@github.com> napisał:
Yes, what Ben said, a screen shot would be helpful. Also, I'm not sure I understand what you mean with the 'star button'. See my screen shot, when you scroll down you hit the 'START SCENARIO' button and it will work as per usual.

**Comment by BenHall** [comment]
@jkaczmarzynski It looks like the screenshot didn't attach or upload correctly to Github.

**Comment by GrahamDumpleton** [comment]
Can we assume this was a transient problem and close issue?

**Comment by mhausenblas** [comment]
Yes, I'd agree. Please let us know if you want it re-opened @jkaczmarzynski
