### ISSUE TITLE
Scenarios for OpenShift Administrators

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift-evangelists/intro-katacoda#119]
I am a writer for OpenShift docs and really like these tutorials. I noticed that all the scenarios listed here are developer focused. I wanted to contribute to this by creating more scenarios for OpenShift Administrators.
But before I start putting effort on any such scenarios, I wanted to confirm that will it be okay to add admin related things here? Maybe a new category for OpenShift Administration. Or if this one is just for the developers and we don't need any admin related stuff in here?

Thanks again for creating these tutorials, they are helpful.

**Comment by thesteve0** [comment]
Hey Guarav:
Great question - I am circling in the main people in case this gets lost in
the regular github email.
Thanks
Steve

**Comment by gshipley** [comment]
I think this would be great.  However, we would need to know what scenarios you plan on creating to ensure that we have a base openshift image that has permissions etc to allow for admin tasks etc.

**Comment by gaurav-nelson** [comment]
To start with, I was thinking about:
1. Cluster Administration (can be broken into two parts)
 - OpenShift Projects
 - User Roles 
 - Tutorial to create users, add permissions, and test them:
 	- Creating users
 	- adding and removing roles for users
 	- restricting project creation
 - adding and removing projects
 - creating applications in projects
 - exploring pods, services, routes etc.
 - scaling applications
 - viewing event logs

2. Protecting information with OpenShift Secrets
 - Secrets use cases
 - creating secretes
 - configmap objects
 - Tutorial to create project and save secrets

I also thought about the following, but do not know if these will be possible with Katakoda:
 - Persistent Storage
 - Adding openshift masters and nodes (and removing masters and nodes)
 - Setting Quotas and Limits
 - OpenShift integration with Clodforms (ManageIQ)

**Comment by gshipley** [comment]
@mhausenblas Do we have an image that supports already or would we need to create a new one?

**Comment by GrahamDumpleton** [comment]
The current images leave the terminal as an admin user from start, so doing admin stuff is not an issue. Where there will be issues is if need multi node cluster, or need to restart OpenShift after changing cluster master config.

Most of the things you mention though I don't see as admin but fall under what normal users do or need to know and can be done with current image. A number of them are already partly covered in existing scenarios, although can still have separate ones and the intent now our new book is effectively done is to create a lot of new scenarios based on topics it covered.

I would suggest proposing a couple of specific scenarios you have in mind to get started and can see how that matches up with own plans for scenarios intend adding. We can then make suggestions of what else could be covered in a scenario done by you based on what we were going to do, or we keep going with what we had in mind and steer you to other topics in your list.

BTW, on specific issue of user creation, the setup we use is that user accounts created as soon as you login, so there isn't much one can show about user management that an admin might do.

If you drop me an internal email I can send you a link to the new book so can see what topics we are covering in it.

**Comment by gaurav-nelson** [comment]
Thanks @thesteve0 @gshipley @GrahamDumpleton 

I am closing this and will take it up in Trello.
