### ISSUE TITLE
Persistent Volume Creation for Postgresql in Two different projects in Openshift origin

### ISSUE THREAD

**Issue by KrishnaKoppineni** [openshift-evangelists/intro-katacoda#134]
I am using open-shift origin in the i just created two projects. One is for development and one  for SIT.
In development project i had installed PostgreSQL with persistent volume application. It is working properly and data will be persisted.

And my requirement is to create the same application in SIT project as PostgreSQL with persistent volume application. I am trying to do it in many ways but i am not get success-ed. when i redeploy the application the data will not be persisted.

So, please provide the solution for this problem as soon as possible.

**Comment by GrahamDumpleton** [comment]
This is not a problem to ask about using OpenShift. It is an issue tracker specifically for problems with using the OpenShift learning portal at learn.openshift.com.

If you have questions about using OpenShift, use StackOverflow or the Google Group at:

* https://groups.google.com/forum/#!forum/openshift
