### ISSUE TITLE
Accessing the host name from one project to another in Open shift origin

### ISSUE THREAD

**Issue by KrishnaKoppineni** [openshift-evangelists/intro-katacoda#135]
I am using the open shift origin. In that i just created the two projects for dev and testing. Each project having the PostgreSQL projects. I need to access these two projects with the host name only from a different project using the Pgadmin4. 

Provide the solution for this soon.

**Comment by GrahamDumpleton** [comment]
This is not a place to ask about using OpenShift. It is an issue tracker specifically for problems with using the OpenShift learning portal at learn.openshift.com.

If you have questions about using OpenShift, use StackOverflow or the Google Group at:

* https://groups.google.com/forum/#!forum/openshift
