### ISSUE TITLE
Metrics not running due to low memory

### ISSUE THREAD

**Issue by e-minguez** [openshift-evangelists/intro-katacoda#137]
Metrics has been working for me since they where merged but today it seems to be failing. I've seen the instance now has 1,5 gb ram, which is not enough for metrics to be deployed.

The image should have at least 2 gb ram https://github.com/openshift-evangelists/intro-katacoda/blob/master/environments/openshift-3-6-metrics/openshift-metrics.json#L22

Thanks.

cc @mhausenblas @BenHall

**Comment by BenHall** [comment]
Sorry, that was my fault. Fixing now.

**Comment by BenHall** [comment]
I moved the metrics start via a different service, but this re-used the main OpenShift config. I've now fixed this. Thanks for highlighting, I forgot this had a 2Gb min.

**Comment by e-minguez** [comment]
Thanks Ben!
