### ISSUE TITLE
Metrics scenario dashboard doesn't work

### ISSUE THREAD

**Issue by e-minguez** [openshift-evangelists/intro-katacoda#138]
Using the metrics scenario https://learn.openshift.com/introduction/using-metrics/ the dashboard button doesn't show the OpenShift web gui.
Opening a new tab in the browser with the proper url works.
cc @BenHall @mhausenblas 
Thanks!

**Comment by e-minguez** [comment]
![screenshot from 2018-02-14 17-22-33](https://user-images.githubusercontent.com/346758/36215177-ab0a380c-11ab-11e8-810b-c54967c53b16.png)

**Comment by BenHall** [comment]
I've added a workaround by removing the iframe aspect. It will now open in a separate tab. 

We'll look into a longer term solution for this.

**Comment by e-minguez** [comment]
Thanks!!! Amazing response time. Thanks Ben!!
