### ISSUE TITLE
Allow for an image to be cached in the startup image

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#16]
We should have the images baked in to the packer image rather than the pull step in the init

**Comment by BenHall** [comment]
Please provide me with a list of images and I will include them

**Comment by jorgemoralespou** [comment]
This is the list of images for openshift itself

````
openshift/origin-sti-builder:v1.4.1
openshift/origin-docker-builder:v1.4.1
openshift/origin-deployer:v1.4.1
openshift/origin-docker-registry:v1.4.1
openshift/origin-haproxy-router:v1.4.1
openshift/origin:v1.4.1
openshift/origin-pod:v1.4.1
origin-recycler:v1.4.1
````

This is the list of images we use for s2i examples:
````
centos/python-35-centos7:latest
````

For the examples:
````
openshiftroadshow/parksmap-katacoda:1.0.0
````

**Comment by thesteve0** [comment]
Sorry to have taken so long on this but I am concerned about two things
1) How do keep the images updated. One balancing point to this is that if some of the base layers are already there then pulling down new ones shouldn't take as long even if we don't update the "vm"
2) We need a way for there to be multiple "base" VMs and call them in the init scripts. Some people from our middleware team want to start doing classes and their images are very large. We don't want out Python or node people to have to download those images in their VM and vice versa.

**Comment by BenHall** [comment]
1. With the way `centos/python-35-centos7:latest` works, I think the best choice is to have as much cached as possible and then only pull down the layers that have changed. It will at least limit some of the bandwidth usage/delays. It's possible to use the `env-init.sh` step to re-pull images in advance so by the time the user tries to access it then the layers should be available. 

2. This is in place with the `index.json` file (https://github.com/openshift-evangelists/intro-katacoda/blob/master/intro-openshift/deploying-images/index.json#L9). We'll need to come up with a solution for building the images, but different image ids can be used, each being customised in advance for the scenario.

**Comment by jorgemoralespou** [comment]
Is there a list of images and the contents of them? 
How can we manage this?
How are images created? How can we collaborate on create various of these?

**Comment by BenHall** [comment]
Here are the currently cached images.

At the moment the best way is by raising Github issues. Longer term, this will be automated.

```
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/hello-openshift                   latest              1c7bcc33b4a0        7 weeks ago         5.635 MB
docker.io/openshift/jenkins-1-centos7                 latest              a92cd325be2f        7 weeks ago         685.2 MB
docker.io/centos/python-35-centos7                    latest              d16d9c076346        7 weeks ago         543.4 MB
docker.io/openshift/base-centos7                      latest              4842f0bd3d61        8 weeks ago         383 MB
docker.io/openshift/hello-openshift                   v1.4.1              6a3dbbd93b84        9 weeks ago         5.635 MB
docker.io/openshift/origin-sti-builder                v1.4.1              6da72734b8da        9 weeks ago         487 MB
docker.io/openshift/origin-docker-builder             v1.4.1              273c4a0a576c        9 weeks ago         487 MB
docker.io/openshift/origin-deployer                   v1.4.1              afc21e7d6e69        9 weeks ago         487 MB
docker.io/openshift/origin-gitserver                  v1.4.1              873fce249a8a        9 weeks ago         450.2 MB
docker.io/openshift/origin-docker-registry            v1.4.1              1acfee35a0f0        9 weeks ago         353.1 MB
docker.io/openshift/origin-haproxy-router             v1.4.1              704fbd840e9b        9 weeks ago         508.5 MB
docker.io/openshift/origin                            v1.4.1              bf6559baa859        9 weeks ago         487 MB
docker.io/openshift/origin-pod                        v1.4.1              a757ae2ce048        9 weeks ago         1.139 MB
docker.io/openshift/mysql-55-centos7                  latest              968db52211da        3 months ago        384.6 MB
docker.io/openshift/origin-metrics-cassandra          v1.4.1              4947def356cc        4 months ago        681.3 MB
docker.io/openshift/origin-metrics-hawkular-metrics   v1.4.1              20611b82aa63        4 months ago        848.7 MB
docker.io/openshift/origin-metrics-heapster           v1.4.1              1cdafb7efb95        4 months ago        1.037 GB
docker.io/openshift/origin-metrics-deployer           v1.4.1              d2d20904e3f2        4 months ago        651.7 MB
docker.io/katacoda/contained-nfs-server               centos7             a1de53f2e68f        5 months ago        247.1 MB
```

**Comment by jorgemoralespou** [comment]
I was asking about VM images as you said in a previous comment in option 2 that you can specify the VM image to use.

**Comment by BenHall** [comment]
Oh, sorry, I thought you meant Docker Images. At the moment there is only one OpenShift Environment but it's setup to support multiple customised environments.

The best way is to create a Github issue defining the customisations required.
