### ISSUE TITLE
A complete list of magic {{ }} and [[ ]]  substitution 

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#17]

**Comment by BenHall** [comment]
There aren't many, but here are the *new* docs pages

https://katacoda.com/docs/scenarios/markdown-syntax

https://katacoda.com/docs/scenarios/displaying-ports

These will be continually updated/improved. 

One thing to note. I have included a new {{copy}} flag as suggested by @GrahamDumpleton - By clicking copy, the value will be placed in the users clipboard.

**Comment by GrahamDumpleton** [comment]
I recollect seeing some scenario for something which brought up some sort of in browser editor for changing files on the host. Was I dreaming?

**Comment by BenHall** [comment]
I believe you're talking about this layout - https://katacoda.com/courses/docker/create-nginx-static-web-server

To use this, in the index.json, change the layout to terminal-editor

Initial docs at https://katacoda.com/docs/scenarios/layouts
