### ISSUE TITLE
Carry out load testing

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#18]

**Comment by BenHall** [comment]
It would be good to know if you have any estimates/expectations of what you'd like? 

I've had 20 users without any problems. I can try and work out the upper-max, but we can add more capacity if there are particular events/workshops being run.

**Comment by thesteve0** [comment]
Well for example, we are doing a summit workshop with 50 participants this
week. Each will be spinning up a couple of Postgresql instances with a
python app server.

Some of our roadshow events are 70 to 100 people.

The problem is how to insure we can spin up the capacity when we need it.

**Comment by BenHall** [comment]
Thanks!! Let me see what happens at 50 people with Postgres running.

**Comment by BenHall** [comment]
We have a new approach for training / large classrooms. Please speak to me offline for details.
