### ISSUE TITLE
Need "VMs" with more memory and disk

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#22]
Some of the new people who want to write scenarios have much larger containers and disk space requirements that we need for some of our intro scenarios. How do we have different size base VMs and call them in the init script. This is related to #16

**Comment by BenHall** [comment]
Replied in #16 too. It's based on the imageid. Different imageids related to different environments, which can be customised as much as required, including the memory available. 

At present, I need to build the images so let's work together on what's required and how it differs from the current base.

**Comment by BenHall** [comment]
I've made a Packer script that reflects the environment. This can control what images and settings are required. I hope this helps.

https://github.com/openshift-evangelists/intro-katacoda/tree/master/environments/openshift

**Comment by thesteve0** [comment]
@mhausenblas This is the issue - I guess what I really need is more doc on how to do this AND some pricing for like a 4 gig RAM VM

**Comment by mhausenblas** [comment]
Thanks @thesteve0!

@BenHall can we discuss this along with the 3.6 move, once you're back in the UK, end of week?

**Comment by thesteve0** [comment]
In terms of what we need for "new images", right now we just need the ability to add docker images to already be present in the built image. We want to avoid pulling down a gig or two of images when the scenario loads.

**Comment by BenHall** [comment]
Email sent.
