### ISSUE TITLE
Clickable links with sub URL path in katacoda.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-evangelists/intro-katacoda#24]
Found this in old email. Haven't tested to see if still an issue.

If I have a clickable link such as:

**https://[[HOST_SUBDOMAIN]]-8443-[[KATACODA_HOST]].environments.katacoda.com/oauth/token/request**

I remember that this used to open in a new window. It seems you may have changed that to use the embedded view in dashboard, which is fine, but I note that in doing that it is ignoring the sub URL path.

That is, it doesn't go to /oauth/token/request path but just brings up the dashboard tab and is not changing to the specified path.

Are there limitations around embedded clickable links?

**Comment by BenHall** [comment]
I'll get this fixed ASAP.

**Comment by BenHall** [comment]
This had been fixed but I forgot to update the ticket. This should now work as expected. Please let me know if you need anything else.
