### ISSUE TITLE
Means to say interrupt and execute new command.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-evangelists/intro-katacoda#29]
Am starting to use ``oc`` commands such as ``oc logs --follow`` and ``oc get --watch``. These commands will not exit unless you do _CTRL-C_ in the terminal window, which you have to tell users to do explicitly. It may be useful to be able to say for a subsequent command:

```
``some-command``{{interrupt+execute}}
```

This would have the effect of sending a SIGINT signal into the interactive terminal session to kill of an existing running command and once that has exited then run the command.

You would only use this where you know you are following up a command which would otherwise keeping running unless interrupted.

**Comment by BenHall** [comment]
Ahh, that's a cool idea!

**Comment by kameshsampath** [comment]
@GrahamDumpleton @BenHall 

In many scenarios we might need the user to run the few commands with doing `CTRL + C` first,
e.g. in my case i was building a scenario for Spring Boot on OpenShift,  where post doing `mvn spring-boot:run` which starts the app in foreground, I would like the user to do `CTRL+C` before doing the next command of `mvn fabric8:deploy` to deploy the application to OpenShift

**Comment by BenHall** [comment]
Sorry for the delay on this. Your comment prompted a spark on how it can be implemented. 

This is being tested now. The syntax will be:

`some-command`{{execute interrupt}}

It will execute Ctrl+C before the main command

**Comment by kameshsampath** [comment]
that should be cool @BenHall  thanks :)

**Comment by BenHall** [comment]
This is now live.

**Comment by kameshsampath** [comment]
awesome! thanks :)

**Comment by danielhelfand** [comment]
@BenHall Is there any way this could be adapted to just run the Ctrl+C? So basically just run Ctrl+C and not execute a command after Ctrl+C. 

Or is there a way to only run Ctrl+C in katacoda that I'm not aware of?

**Comment by BenHall** [comment]
No, but you can do some workarounds, such as

`: stopped`{{execute interrupt}} or `clear`{{execute interrupt}}
