### ISSUE TITLE
Getting Could not check CSRF token. Please try again.

### ISSUE THREAD

**Issue by merandall** [openshift-evangelists/intro-katacoda#40]
Trying the "Getting Started with OpenShift for Developers" tutorial and when trying to login to the console receiving error message: "Could not check CSRF token. Please try again."

**Comment by GrahamDumpleton** [comment]
The katacoda site we use to host this on was having some issues earlier. I believe this is resolved now so try again. If still have issues, let us know which browser you are using and on what platform. Thanks.

**Comment by BenHall** [comment]
Thanks for letting us know. After investigating this alongside #41 it looks to be related to 3rd party cookies being blocked. We're looking at how Katacoda can fix this. Thanks for letting us know. I've discussed a workaround in the other issue in the meantime but we're working on a longer term solution now.

**Comment by BenHall** [comment]
This should now have been fixed. If 3rd party cookies are blocked then the dashboard is displayed in a separate tab.
