### ISSUE TITLE
Seems like a issue with using "Getting Started with OpenShift for Developers"  Tutorial

### ISSUE THREAD

**Issue by tammana** [openshift-evangelists/intro-katacoda#41]
Trying the "Getting Started with OpenShift for Developers" tutorial and when trying to login to the console receiving error message: "Could not check CSRF token. Please try again."

**Comment by BenHall** [comment]
Thanks for letting us know. Could you please let me know your browser / OS version. Are you running behind and VPN or proxy?

**Comment by BenHall** [comment]
Could you please confirm that if you attempt to login a second time it also fails?

**Comment by tammana** [comment]
Yes.... I tried multiple times and results in the same error.

ThanksSuresh 



On Tuesday, July 25, 2017, 1:54:47 PM PDT, Ben Hall <notifications@github.com> wrote:


Could you please confirm that if you attempt to login a second time it also fails?

**Comment by tammana** [comment]
I am using Safari and not on any VPN.

Thanks Suresh 



On Tuesday, July 25, 2017, 1:49:07 PM PDT, Ben Hall <notifications@github.com> wrote:


Thanks for letting us know. Could you please let me know your browser / OS version. Are you running behind and VPN or proxy?

**Comment by BenHall** [comment]
Thanks for the information. It appears to be related to Safari, 3rd party cookies and our (Katacoda) use of iFrames.

As a workaround, load the dashboard in a separate tab by clicking the arrow and loading port 8443 as shown below.

![screenshot 2017-07-25 22 06 21](https://user-images.githubusercontent.com/82614/28593786-90eca174-7185-11e7-8680-1d5798ee6f22.png)

We'll work on a longer term solution. Thank you for your help on this.

**Comment by tammana** [comment]
ThanksBen. Your pointer addressed the problem.
 Suresh 


On Tuesday, July 25, 2017, 2:07:51 PM PDT, Ben Hall <notifications@github.com> wrote:


Thanks for the information. It appears to be related to Safari, 3rd party cookies and our (Katacoda) use of iFrames.

As a workaround, load the dashboard in a separate tab by clicking the arrow and loading port 8443 as shown below.



We'll work on a longer term solution. Thank you for your help on this.

**Comment by BenHall** [comment]
This should now have been fixed. If 3rd party cookies are blocked then the dashboard is displayed in a separate tab instead of being displayed inline.

Thanks for letting us know.
