### ISSUE TITLE
Problem with insecure web socket

### ISSUE THREAD

**Issue by mathiask** [openshift-evangelists/intro-katacoda#42]
The Interactive Learning Portal worked for me two days ago, but today I get the following warnings in the console log:

VM417:35 Mixed Content: The page at 'https://learn.openshift.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://learn.openshift.com:1313/livereload'. This request has been blocked; this endpoint must be available over WSS.
WrappedWebSocket @ VM417:35
VM417:35 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at WrappedWebSocket (<anonymous>:35:21)
    at e.n.Connector.e.connect (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:1848)
    at new e (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:1495)
    at new e (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:6177)
    at Object.<anonymous> (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:19616)
    at Object.8../customevents (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:20040)
    at i (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:254)
    at e (https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:425)
    at https://learn.openshift.com/livereload.js?port=1313&mindelay=10:1:443

As a consequence I can no longer start any of the tutorial scenarios.

**Comment by BenHall** [comment]
I'm looking into this now.

**Comment by BenHall** [comment]
The livereload issue shouldn't be causing issues. When you say the tutorials can't start, are you getting an error message?

**Comment by mathiask** [comment]
No, nothing happens when I click on any of them. There is no error message. I only saw the message I pasted above when I opened the developer tools in Chrome. 

Of course, I cannot exclude that there were also JS errors when it still worked as I didn't check the Chrome console then.

**Comment by mathiask** [comment]
I have to retry later from home to exclude that it is an issue with our corporate network (I accessed it successfully from the work network before, though).

**Comment by BenHall** [comment]
Yes please, that would be very helpful.

Can you access the links directly? https://learn.openshift.com/introduction/getting-started/

**Comment by mathiask** [comment]
I can access the tutorials from my home network: the "Start Scenario" links are active start the scenario in a new tab.

Interestingly, opening the developer console, I see the same error concerning insecure WebSockets. So this is not the root cause, but something seems to be off.

I can (unsurprisingly) access the link also directly, However, in the console I see the same WebSocket issue again.

I'll try tomorrow from the other network if the direct links work also from there.

**Comment by BenHall** [comment]
Thanks for the update!

**Comment by mathiask** [comment]
I can no longer reproduce the problem. All links are working now (error messages in the console are still there but do not seem to cause any other issues). The same is true for my colleague who had the same problem.
I close the issue.
