### ISSUE TITLE
EAP Kills the OpenShift katacoda instance

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#51]
When I try to run JBoss EAP in Katacoda it kills the entire Katacoda instance. I can't debug because everything becomes unresponsive. Can I please get some information on what is happening when you do the following

oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json -n <yourprojectname>

oc new-app jboss-eap70-openshift~https://github.com/thesteve0/scalingdemo.git

Wait a while and the build completes and the deployment

Actually it worked this time so keep this issue open and assigned to me while I try to reproduce the error.

Thanks

**Comment by BenHall** [comment]
This sounds like a OOM and/or you're hitting the expiry for the environment depending on how long it takes to deploy.

Please try with the new 4Gb image (#54).

**Comment by thesteve0** [comment]
Works now thanks!
