### ISSUE TITLE
Layout for learn.openshift.com for middleware stuff

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#53]
We are about to hopefully add 10 - 12 middleware katacoda scenarios. Perhaps we should do some different layout on the front page to organize it better. 

Perhaps rows or columns for different topics, and then the ability to have a "more..." at the bottom that brings you to a full page of middleware scenarios?

@mhausenblas @GrahamDumpleton @BenHall

**Comment by BenHall** [comment]
From the viewpoint of headers/different topics, this is part of the static HTML in the repo. You can see an example of having two different dashboards on the same page at https://learn.openshift.com/category-example/

If you would like paging/load more, let me know and we can add this.
