### ISSUE TITLE
Need instructions on how to make a katacoda image

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#54]
Hey there - we need instructions on how to:
1) create a new katacoda image that we can use for middleware. By this I mean detailed instructions on how to specify the file, build it, and then get it available on the site
2) Change resource consumption (right now just up it to 4 gigs) along with telling katacoda how to pull the new "middleware" image

@mhausenblas  assign as needed

**Comment by BenHall** [comment]
Hey Steve, I'll put this together next week

**Comment by BenHall** [comment]
I've uploaded some starting points for the image creation. 

If you add the customisations to https://github.com/openshift-evangelists/intro-katacoda/blob/master/environments/openshift-middleware/scripts/middleware.sh then I can build you the new environment. 

This is just a bash file, assume that OpenShift and attached images have been setup and configured (done in other scripts). 

When creating new scenarios, use the image id `openshift-middleware` in the index.json file. It's available for use on the test server. It's the same as the main Openshift image, but with 4GB of memory.

**Comment by thesteve0** [comment]
I have reports that the openshift-middeware images are not working.

**Comment by thesteve0** [comment]
![image](https://user-images.githubusercontent.com/1404099/30890788-dccaf732-a2e3-11e7-8dcd-f44013bb4dc7.png)

Definitely not working and I need to get EAP up and running can we please move on this fast @BenHall  @mhausenblas

**Comment by BenHall** [comment]
@thesteve0 I'm very sorry. I completely missed your comment original comment.

This has been fixed. I overlooked one configuration part in the system to make images "public".
