### ISSUE TITLE
Courses only picked in master branch

### ISSUE THREAD

**Issue by galderz** [openshift-evangelists/intro-katacoda#60]

**Comment by GrahamDumpleton** [comment]
How are you referring to a branch?

I have not tried, but understand is that if you want to use a branch, in the profile settings of your katacoda account, add ``#branch`` at end of GitHub Scenario Repository setting.

![image](https://user-images.githubusercontent.com/507637/30575715-f361f752-9d02-11e7-9997-300f9ad7a87d.png)

**Comment by e-minguez** [comment]
I can confirm this works.
