### ISSUE TITLE
Logging in as user "developer" actually logs in as user "root"

### ISSUE THREAD

**Issue by oddvart** [openshift-evangelists/intro-katacoda#61]
$ oc login
Authentication required for https://172.17.0.84:8443 (openshift)
Username: developer
Password:
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ whoami
root
$

**Comment by oddvart** [comment]
Actually, "oc login" does not change user at all, and any user/password seems to be acceptable:

$ ~/.launch.sh
Starting OpenShift
Waiting for OpenShift to start... This may take a couple of moments
OpenShift started.
Configuring... OpenShift Ready
$ whoami
root
$ oc login
Authentication required for https://172.17.0.76:8443 (openshift)
Username: developer
Password:
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ whoami
root
$ oc login
Authentication required for https://172.17.0.76:8443 (openshift)
Username: asdf
Password:
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ whoami
root
$

**Comment by GrahamDumpleton** [comment]
That is totally normal.

The UNIX account you are in on the host you run the oc client is ``root``.

When you run ``oc login``, you aren't changing the local user. You are logging into the OpenShift cluster, which all it does is cache credentials so future commands work against the cluster. You aren't creating a login shell on the cluster.

The simplistic way that OpenShift is deployed for the tutorials means any login/password combination will work. To make it simpler we just always say to use developer/developer. We at least need to do that else will be accessing it as admin account, which can't log in as in web console.

**Comment by GrahamDumpleton** [comment]
And the command you want to use to see who you are logged into OpenShift as is:

```
oc whoami
```

**Comment by GrahamDumpleton** [comment]
Don't believe there is any issue here, closing.
