### ISSUE TITLE
my site does not open

### ISSUE THREAD

**Issue by okadirkartal** [openshift-evangelists/intro-katacoda#65]
my site does not open
 i restarted the server on openshift  for many times
okkartal.com

**Comment by GrahamDumpleton** [comment]
@okadirkartal This is not a general help forum for OpenShift, but just a place to report issues with our interactive learning environment at learn.openshift.com.

If you need help with OpenShift Online you can use community forums such as StackOverflow or the Google Group for OpenShift (https://groups.google.com/forum/#!forum/openshift).
