### ISSUE TITLE
Background download of docker images doesn't work

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#7]
We tried adding the pull commands to 

https://github.com/openshift-evangelists/intro-katacoda/blob/master/intro-openshift/getting-started/env-init.sh

But we are not seeing it work. We think you could add it to launch.sh and background it but we leave the implementation to you. Ping us if you want to discuss this.

Thanks!

**Comment by thesteve0** [comment]
Was the order of the commands important because we tried this all sorts of
ways before and it didn't work

**Comment by BenHall** [comment]
Potentially. If one the commands fail then it causes later commands to not be run. I'm think the registry failed because the server hasn't finished booting. 

This is an intermediate step to improve things. I'm going to spend some more time on this area tomorrow/weekend.

**Comment by thesteve0** [comment]
Ahhh good to know - thanks
