### ISSUE TITLE
How to change 'Start Scenario' and background panel in tile in branded ui.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-evangelists/intro-katacoda#71]
How can we do the same as the 'Playground' tile in:

* https://katacoda.com/courses/kubernetes

so we can do a similar distinguished item different to normal scenario.

We can then have separate playgrounds for OpenShift 3.6 and OpenShift 3.7 with service catalog.

**Comment by BenHall** [comment]
We only support changing the name for everything at the moment. Will schedule feature and get back to you.
