### ISSUE TITLE
oc cluster up fails

### ISSUE THREAD

**Issue by BenHall** [openshift-evangelists/intro-katacoda#74]
The reason we did write-config / start instead of `cluster up` was speed/ability to set masterPublicURL etc to the public domain.

To try and resolve the login issue, I attempted to run it.

```
$ oc cluster up
<snip>
Waiting for API server to start listening
   OpenShift server started
FAIL
   Error: cannot create container using image openshift/origin:v3.7.0-rc.0
   Caused By:
     Error: Error response from daemon: {"message":"devmapper: Error activating devmapper device for 'c58bd7233500ce0d44e40564d7425acc428761e3f06e01990832c7b955906eda-init': devicemapper: Can't set cookie dm_task_set_cookie failed"}
```

**Comment by jorgemoralespou** [comment]
@BenHall What version of docker are u using? What host OS are you using?

**Comment by BenHall** [comment]
3.7 rc0. Centos OS 7 I believe.

Potentially related to having already run oc before...

On 15 Nov 2017 10:47 am, "Jorge Morales Pou" <notifications@github.com>
wrote:

@BenHall <https://github.com/benhall> What version of docker are u using?
What host OS are you using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift-evangelists/intro-katacoda/issues/74#issuecomment-344540138>,
or mute the thread

**Comment by BenHall** [comment]
Looks like this was due to a previous OpenShift installation being on the machine.
