### ISSUE TITLE
Upgrade to 3.7?

### ISSUE THREAD

**Issue by BenHall** [openshift-evangelists/intro-katacoda#85]
We have two images, Openshift and OpenShift Middleware.

When should we upgrade to 3.7? In particular, should 5th Dec be using 3.7?

@tqvarnst  @jamesfalkner @thesteve0 @mhausenblas @GrahamDumpleton

**Comment by jamesfalkner** [comment]
I'm ok with upgrading, as long as we have a day or two to test, and you're willing to roll it back very quickly in case of problems :)

**Comment by thesteve0** [comment]
There might be screen updates as well. The only one that matters right now
is FIS

**Comment by mhausenblas** [comment]
For this particular upgrade, I let Middleware decide what they prefer since they've got that important event coming up. Also, why are we still using the issue tracker here? We should be using Trello.

**Comment by GrahamDumpleton** [comment]
I am confused why this is being asked. One of the main reasons for being able to select the image name for individual scenarios was so we could convert them one at a time when we can. There was no intention to upgrade everything to 3.7 in one go. I would only be even starting to change them, one at a time, after the 12th December as I have no time before then.

We also still need a 3.7 image with template service broker enabled. Now that 3.7 GA is out, the question is whether template service broker runs out of the box or not.

**Comment by BenHall** [comment]
Good point! Sorry, I wasn't clear and jumping ahead of myself.

My main question was for the middleware image as somewhat time sensitive.

I had imagined the main scenarios would be moved one at a time as we have
discussed.
