### ISSUE TITLE
Dashboard returns 504: Gateway Time-Out 

### ISSUE THREAD

**Issue by cjam** [openshift-evangelists/intro-katacoda#97]
I'm going through the [initial tutorial](https://learn.openshift.com/introduction/getting-started/) and the Dashboard tab doesn't ever load the OpenShift web interface,  eventually times outs with a 504.

Reloaded the page a few times to no avail.

**Comment by BenHall** [comment]
Thank you for letting us know. We've resolved the issue and you should be able to load the dashboard now. Please let us know if you continue to have problems.

**Comment by thesteve0** [comment]
Thanks for the alert - should be resolved. Please let us know if it is not

**Comment by cjam** [comment]
Confirmed.  Dashboard is working.  Wow that was fast.

**Comment by cherfongfoo** [comment]
Hi, Now I am having the same issue where the Dashboard tab is showing 504. Refreshing does not help either.

**Comment by BenHall** [comment]
@cherfongfoo Could you please retry.

**Comment by BenHall** [comment]
@cherfongfoo Which scenario are you taking?
